# Latest documentation available at https://omines.github.io/datatables-bundle/#configuration
datatables:
    language_from_cdn:    false

    # Set options, as documented at https://datatables.net/reference/option/
    options:
#        lengthMenu : [10, 25, 50, 100, 250, 500, 1000, 2500]
        lengthMenu : [10, 25, 50, 100]
        pageLength: 10
        searching: true
        dom: '<lf<t>ip>'
#        dom: "<'row' <'col-sm-12' tr>><'row' <'col-sm-6'l><'col-sm-6 text-right'pi>>"

    template_parameters:
        # Example classes to integrate nicely with Bootstrap 3.x
        className: 'table table-striped table-bordered table-hover data-table'
        columnFilter: 'thead'

    # You can for example override this to "tables" to keep the translation domains separated nicely
#    translation_domain: 'messages'
    translation_domain: 'prompts'
